# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
    . ~/.bashrc
fi

# Get profile file
if [ -f ~/.profile ]; then
    source ~/.profile
fi

# User specific environment and startup programs

PATH=$PATH:$HOME/bin:~/.composer/vendor/bin:/usr/local/bin


export PATH
