---
- name: Add memcached to chkconfig
  command: chkconfig --add memcached
  changed_when: false
  failed_when: false

- name: Auto start memcached
  command: chkconfig --levels 235 memcached on
  notify: restart memcached
  changed_when: false
  failed_when: false
