---
- name: add bash_profile file
  become: true
  become_user: vagrant
  template:
    src: bash_profile
    dest: ~/.bash_profile

- name: add bashrc file
  become: true
  become_user: vagrant
  template:
    src: bashrc
    dest: ~/.bashrc
  changed_when: false

- name: insert custom bash scripts
  become: true
  become_user: vagrant
  lineinfile:
    path: ~/.bashrc
    line: '{{ item }}'
    insertafter: 'EOF'
  with_items: "{{ bash | default([]) }}"
  changed_when: false
