---
- name: install php 7.2
  yum:
    name: "{{ packages }}"
    state: latest
    enablerepo: remi,remi-php72
  vars:
    packages:
    - php72
    - php72-php-mbstring
    - php72-php-pdo
    - php72-php-mysqlnd
    - php72-php-intl
    - php72-php-bcmath
    - php72-php-soap
    - php72-php-pecl-xdebug
    - php72-php-xml
    - php72-php-zip
    - php72-php-pecl-memcache
    - php72-php-pecl-memcached
    - php72-php-fpm

- name: set access log file
  file:
    state: directory
    path: /var/log/php-fpm
    mode: 0777

- name: php.ini file
  template:
    src: php.ini
    dest: /etc/opt/remi/php72/php.ini

- name: www.cnf file
  template:
    src: www.conf
    dest: /etc/opt/remi/php72/php-fpm.d/www.conf

- name: create php session directory
  file:
    state: directory
    path: /var/lib/php/session
    mode: 0777

- name: set access log file
  file:
    state: touch
    dest: /var/log/php-fpm/access.log
    mode: 0777

- name: set error log file
  file:
    state: touch
    dest: /var/log/php-fpm/error.log
    mode: 0777

- name: set slow log file
  file:
    state: touch
    dest: /var/log/php-fpm/slow.log
    mode: 0777

- name: start php-fpm
  service:
    name: php72-php-fpm
    state: started
    enabled: true

- name: enable php72
  template:
    src: enablephp72.sh
    dest: /etc/profile.d/enablephp72.sh
