---
- name: install php 7.3
  yum:
    name: "{{ packages }}"
    state: latest
    enablerepo: remi,remi-php73
  vars:
    packages:
    - php73
    - php73-php-mbstring
    - php73-php-pdo
    - php73-php-mysqlnd
    - php73-php-intl
    - php73-php-bcmath
    - php73-php-soap
    - php73-php-pecl-xdebug
    - php73-php-xml
    - php73-php-zip
    - php73-php-pecl-memcache
    - php73-php-pecl-memcached
    - php73-php-fpm

- name: set access log file
  file:
    state: directory
    path: /var/log/php-fpm
    mode: 0777

- name: php.ini file
  template:
    src: php.ini
    dest: /etc/opt/remi/php73/php.ini

- name: xdebug.ini file
  template:
    src: xdebug.ini
    dest: /etc/opt/remi/php73/php.d/15-xdebug.ini
  when: xdebug|d(False) == True

- name: www.cnf file
  template:
    src: www.conf
    dest: /etc/opt/remi/php73/php-fpm.d/www.conf

- name: create php session directory
  file:
    state: directory
    path: /var/lib/php/session
    mode: 0777

- name: set access log file
  file:
    state: touch
    dest: /var/log/php-fpm/access.log
    mode: 0777
  changed_when: false

- name: set error log file
  file:
    state: touch
    dest: /var/log/php-fpm/error.log
    mode: 0777
  changed_when: false

- name: set slow log file
  file:
    state: touch
    dest: /var/log/php-fpm/slow.log
    mode: 0777
  changed_when: false

- name: start php-fpm
  service:
    name: php73-php-fpm
    state: started
    enabled: true

- name: enable php73
  template:
    src: enablephp73.sh
    dest: /etc/profile.d/enablephp73.sh
