---
- name: Create MySQL configuration file
  template: src=my.cnf.j2 dest=/etc/my.cnf
  changed_when: false
  failed_when: false

- name: Set custom mysqld configuration
  lineinfile:
    path: /etc/my.cnf
    line: '{{item.setting}}={{item.value}}'
    insertafter: '\[mysqld\]'
  with_items: "{{ mysqld | default([]) }}"
  changed_when: false

- name: Set custom mysqld_safe configuration
  lineinfile:
    path: /etc/my.cnf
    line: '{{item.setting}}={{item.value}}'
    insertafter: '\[mysqld_safe\]'
  with_items: "{{ mysqld_safe | default([]) }}"
  changed_when: false

- name: Set custom client configuration
  lineinfile:
    path: /etc/my.cnf
    line: '{{item.setting}}={{item.value}}'
    insertafter: '\[client\]'
  with_items: "{{ client | default([]) }}"
  changed_when: false

- name: Start the MySQL service
  service:
    name: mysqld
    state: started
    enabled: true

- name: Temp Root Config
  shell: grep "temporary password" /var/log/mysqld.log | cut -d ' ' -f 11
  register: temporary_mysql_password
  changed_when: false
  failed_when: false

- name: Create root MySQL configuration file
  template:
    src: my-default-root.cnf.j2
    dest: ~/.my.cnf
  changed_when: false
  failed_when: false

- name: testusers
  shell: mysql --connect-expired-password -e "ALTER USER USER() IDENTIFIED BY '#!SomeLongPassword1234'"
  changed_when: false
  failed_when: false

- name: update mysql root password for all root accounts
  mysql_user: name={{ mysql_root_db_user }} host={{ item }} password={{ mysql_root_db_pass }} priv='*.*:ALL,GRANT' login_user='root' login_password='#!SomeLongPassword1234'
  with_items:
   - '%'

- name: Create root user MySQL configuration file
  template:
    src: my-root.cnf.j2
    dest: ~/.my.cnf
  notify: restart mysql
  changed_when: false
  failed_when: false

- name: Make the input settings less likely to destroy a whole SQL query
  template: src=editrc dest=~/.editrc

- name: Create vagrant user MySQL configuration file
  become: true
  become_user: vagrant
  template:
    src: my-root.cnf.j2
    dest: ~/.my.cnf
  notify: restart mysql

- name: ensure anonymous users are not in the database
  mysql_user:
    name: ''
    host: localhost
    state: absent
    login_user: 'root'
    login_password: '#!SomeLongPassword1234'
