---
- name: Find PHP
  find:
    paths: /usr/bin/
    patterns: ^php[0-9]+$
    use_regex: yes
    file_type: link
  register: php_binarys

- name: Install PHP Composer
  get_url:
    url: https://getcomposer.org/composer.phar
    dest: /usr/local/bin/composer
    mode: 0755

- name: Remove Global Phing
  become: true
  become_user: vagrant
  shell: "{{ item.path }} /usr/local/bin/composer global remove phing/phing"
  with_items: "{{ php_binarys.files }}"
  register: response
  changed_when: false
  failed_when: "response.stdout and not 'Could not read ./composer.json' in response.stderr"

- name: Install Global Phing
  become: true
  become_user: vagrant
  shell: "{{ item.path }} /usr/local/bin/composer global require phing/phing"
  with_items: "{{ php_binarys.files }}"
  changed_when: false
